let targetEl = null;
const getEl = id => document.getElementById(id);
const getVal = id => getEl(id)?.value?.trim();
const setStorage = (id, val) => localStorage.setItem(id, val);
const loadStorage = id => { if(localStorage.getItem(id) && getEl(id)) getEl(id).value = localStorage.getItem(id); };
const toggleEditable = (state) => document.querySelectorAll('.editable').forEach(el => state ? el.setAttribute('contenteditable', 'true') : el.removeAttribute('contenteditable'));
const updateToolbarPos = (el, box) => { const r = el.getBoundingClientRect(); box.classList.remove('hidden'); box.style.top = `${r.top + window.scrollY - 42}px`; box.style.left = `${r.left + window.scrollX}px`; };
const cleanStyles = el => ['ds-tagline', 'ds-display', 'ds-headline', 'ds-subheadline', 'ds-body'].forEach(c => el.classList.remove(c));

const commitToGit = async (token, repo) => { const btn = getEl('github-save-btn'); btn.textContent = '⏳ ĐANG LƯU...'; btn.disabled = true; try { const clone = document.documentElement.cloneNode(true); clone.querySelector('#editor-ui')?.remove(); clone.body.lastElementChild?.remove(); clone.querySelectorAll('.editable').forEach(el => el.removeAttribute('contenteditable')); const resGet = await fetch(`https://api.github.com/repos/${repo}/contents/index.html`, { headers: { 'Authorization': `token ${token}` } }); let sha = resGet.ok ? (await resGet.json()).sha : null; const resPut = await fetch(`https://api.github.com/repos/${repo}/contents/index.html`, { method: 'PUT', headers: { 'Authorization': `token ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'CMS Auto Update Content', content: btoa(unescape(encodeURIComponent('<!DOCTYPE html>\n' + clone.outerHTML))), sha: sha, branch: 'main' }) }); alert(resPut.ok ? '🚀 Đã đồng bộ index.html lên GitHub thành công!' : '❌ Lỗi GitHub API. Kiểm tra quyền Token.'); } catch(e) { alert('❌ Thất bại: ' + e.message); } finally { btn.textContent = '⚡ LƯU LÊN GITHUB'; btn.disabled = false; } };

window.addEventListener('DOMContentLoaded', () => { loadStorage('idx-gh-token'); loadStorage('idx-gh-repo'); const tgl = document.createElement('button'); tgl.innerHTML = 'Chế Độ Sửa: 🔴 TẮT'; tgl.style.cssText = 'position:fixed;bottom:20px;right:20px;background:#222;color:#fff;border:1px solid #444;padding:12px 24px;border-radius:50px;cursor:pointer;z-index:100000;font-size:13px;font-weight:bold;'; document.body.appendChild(tgl); let mode = false; tgl.onclick = () => { mode = !mode; tgl.innerHTML = mode ? 'Chế Độ Sửa: 🟢 BẬT' : 'Chế Độ Sửa: 🔴 TẮT'; tgl.style.background = mode ? '#00F0FF' : '#222'; tgl.style.color = mode ? '#000' : '#fff'; toggleEditable(mode); if(!mode) getEl('inline-toolbar').classList.add('hidden'); }; document.querySelectorAll('.editable').forEach(el => el.onfocus = (e) => { if(!mode) return; targetEl = e.target; updateToolbarPos(targetEl, getEl('inline-toolbar')); }); getEl('style-selector').onchange = (e) => { if(targetEl && e.target.value) { cleanStyles(targetEl); targetEl.classList.add(e.target.value); } }; getEl('github-save-btn').onclick = () => { const tk = getVal('idx-gh-token'), rp = getVal('idx-gh-repo'); if(!tk || !rp) return alert('Vui lòng điền đủ Token và Repo!'); setStorage('idx-gh-token', tk); setStorage('idx-gh-repo', rp); commitToGit(tk, rp); }; });